### ISSUE TITLE
Warning: Method definition kwcall overwritten

### ISSUE THREAD

**Issue by jalcam** [OpenModelica/OMJulia.jl#115]
I installed OMJulia and received this warnings about overwritten methods definition:

Precompiling project...
  114 dependencies successfully precompiled in 261 seconds. 199 already precompiled.
  1 dependency had warnings during precompilation:
┌ OMJulia [0f4fe800-344e-11e9-2949-fb537ad918e1]
│  WARNING: Method definition ModelicaSystem(OMJulia.OMCSession) in module OMJulia at /home/juanjose/.julia/packages/OMJulia/rKADx/src/modelicaSystem.jl:71 overwritten at /home/juanjose/.julia/packages/OMJulia/rKADx/src/modelicaSystem.jl:138.
│    ** incremental compilation may be fatally broken for this module **
│  
│  WARNING: Method definition kwcall(Any, typeof(OMJulia.ModelicaSystem), OMJulia.OMCSession) in module OMJulia at /home/juanjose/.julia/packages/OMJulia/rKADx/src/modelicaSystem.jl:71 overwritten at /home/juanjose/.julia/packages/OMJulia/rKADx/src/modelicaSystem.jl:138.
│    ** incremental compilation may be fatally broken for this module **
└  

Function defined in Line 71 of modelicaSystem.jl:

<pre>function ModelicaSystem(omc::OMCSession,
                        fileName::AbstractString = nothing,
                        modelName::AbstractString = nothing,
                        library::Union{&lt;:AbstractString, Tuple{&lt;:AbstractString, &lt;:AbstractString}, Array{&lt;:AbstractString}, Array{Tuple{&lt;:AbstractString, &lt;:AbstractString}}, Nothing} = no<span style="background-color:#F8F8F2"><font color="#282A36">&gt;</font></span>
                        commandLineOptions::Union{&lt;:AbstractString, Nothing} = nothing,
                        variableFilter::Union{&lt;:AbstractString, Nothing} = nothing)

<font color="#75D7EC">    ## check for commandLineOptions</font>
    setCommandLineOptions(omc, commandLineOptions)

<font color="#75D7EC">    ## set default command Line Options for linearization as</font>
<font color="#75D7EC">    ## linearize() will use the simulation executable and runtime</font>
<font color="#75D7EC">    ## flag -l to perform linearization</font>
    sendExpression(omc, &quot;setCommandLineOptions(\&quot;--linearizationDumpLanguage=julia\&quot;)&quot;)
    sendExpression(omc, &quot;setCommandLineOptions(\&quot;--generateSymbolicLinearization\&quot;)&quot;)

    omc.filepath = fileName
    omc.modelname = modelName
    omc.variableFilter = variableFilter

<font color="#75D7EC">    #loadFile and set temporary directory</font>
    loadFile(omc, fileName)

<font color="#75D7EC">    #set temp directory for each modelica session</font>
    setTempDirectory(omc)

<font color="#75D7EC">    #load Libraries provided by users</font>
    loadLibrary(omc, library)

<font color="#75D7EC">    # build the model</font>
    buildModel(omc)
end
</pre>

Function defined in Line 138 of the same file:
<pre>function ModelicaSystem(omc::OMCSession;
    modelName::AbstractString=nothing,
    library::Union{&lt;:AbstractString,Tuple{&lt;:AbstractString,&lt;:AbstractString},Array{&lt;:AbstractString},Array{Tuple{&lt;:AbstractString,&lt;:AbstractString}},Nothing}=nothing,
    commandLineOptions::Union{&lt;:AbstractString,Nothing}=nothing,
    variableFilter::Union{&lt;:AbstractString,Nothing}=nothing)

    if isnothing(modelName)
        return println(&quot;\&quot;ModelicaSystem()\&quot; constructor requires modelName&quot;)
    end

<font color="#75D7EC">    ## check for commandLineOptions</font>
    setCommandLineOptions(omc, commandLineOptions)

<font color="#75D7EC">    ## set default command Line Options for linearization as</font>
<font color="#75D7EC">    ## linearize() will use the simulation executable and runtime</font>
<font color="#75D7EC">    ## flag -l to perform linearization</font>
    sendExpression(omc, &quot;setCommandLineOptions(\&quot;--linearizationDumpLanguage=julia\&quot;)&quot;)
    sendExpression(omc, &quot;setCommandLineOptions(\&quot;--generateSymbolicLinearization\&quot;)&quot;)

    omc.modelname = modelName
    omc.variableFilter = variableFilter

<font color="#75D7EC">    #set temp directory for each modelica session</font>
    setTempDirectory(omc)

<font color="#75D7EC">    #load Libraries provided by users</font>
    loadLibrary(omc, library)

<font color="#75D7EC">    # build the model</font>
    buildModel(omc)
end
</pre>

**Comment by AnHeuermann** [comment]
I think I fixed that with https://github.com/OpenModelica/OMJulia.jl/pull/114 but didn't create a new release.

What version of OMJulia did you install? The master or v0.3.0?

**Comment by jalcam** [comment]
Thank you for your answer. OMJulia version is 0.3.0

<pre><font color="#9B6BDF"><b>(@v1.9) pkg&gt; </b></font>status
<font color="#42E66C"><b>Status</b></font> `~/.julia/environments/v1.9/Project.toml`
  <font color="#7A7A7A">[7c7805af] </font>Clapeyron v0.5.7
  <font color="#7A7A7A">[8f4d0f93] </font>Conda v1.10.0
  <font color="#7A7A7A">[0c46a032] </font>DifferentialEquations v7.11.0
  <font color="#7A7A7A">[7073ff75] </font>IJulia v1.24.2
  <font color="#7A7A7A">[682c06a0] </font>JSON v0.21.4
  <font color="#7A7A7A">[961ee093] </font>ModelingToolkit v8.73.1
  <font color="#7A7A7A">[cb905087] </font>Modia v0.12.1
  <font color="#7A7A7A">[0f4fe800] </font>OMJulia v0.3.0
  <font color="#7A7A7A">[c3e4b0f8] </font>Pluto v0.19.32
</pre>
