### ISSUE TITLE
Call command shell on windows using API.system

### ISSUE THREAD

**Issue by olivleno** [OpenModelica/OMJulia.jl#122]
I'd want to copy the result file to a new loaction and tried the following:
```
sendExpression(omc,"system(\"copy model_res.csv model_ref.csv)")
```
and got 
```
ERROR: OMJulia.Parser.LexerError("Error while lexing")
Stacktrace:
 [1] tokenize(data::String)
   @ OMJulia.Parser C:\Users\leo2rng\.julia\packages\OMJulia\ZS3rq\src\lexer.jl:172
 [2] parseOM
   @ C:\Users\leo2rng\.julia\packages\OMJulia\ZS3rq\src\parser.jl:127 [inlined]
 [3] sendExpression(omc::OMJulia.OMCSession, expr::String; parsed::Bool)
   @ OMJulia C:\Users\leo2rng\.julia\packages\OMJulia\ZS3rq\src\sendExpression.jl:85
 [4] sendExpression(omc::OMJulia.OMCSession, expr::String)
   @ OMJulia C:\Users\leo2rng\.julia\packages\OMJulia\ZS3rq\src\sendExpression.jl:74
```

The command `copy model_res.csv model_ref.csv` executed in a windows cmd shell works. Why not using system()?

**Comment by perost** [comment]
You're missing a `\"` to terminate the argument string to `system`:
```
sendExpression(omc,"system(\"copy model_res.csv model_ref.csv)")
                                                             ^
```

**Comment by olivleno** [comment]
Thank you very much for looking into this. It got the \" correct now.

But then stumbled over escaping \, which has to be escaped as \\\\ as described in the sendExpression help.
The following command to fails:
`sendExpression(omc,"system(\"copy model_res.csv ..\\results\\model_ref.csv\")")`

and has to be written as:
`sendExpression(omc,"system(\"copy model_res.csv ..\\\\results\\\\model_ref.csv\")")`
or
`sendExpression(omc,"system(\"copy model_res.csv ../results/model_ref.csv\")")`

This is really annoying as one cannot reuse the path strings used otherwise, but at least it's now clear how it works.

**Comment by olivleno** [comment]
Here comes the solution using `raw`:
`sendExpression(omc,raw"system(\"copy model_res.csv ..\\results\\model_ref.csv\")")`
which turns the string into a raw string without processing the escape sequences.

**Comment by AnHeuermann** [comment]
Julia can call system commands directly, so why send it to omc in the first case? Also not that some of the shell commands send via omc aren't behaving as one would expect, e.g. some prints.

> This is really annoying as one cannot reuse the path strings returned from joinpath(), but at least it's now clear how it works.

Escaping expressions in `sendExpression` is horrible. You could use `OMJulia.API` instead. It will do it for you. But there is no function for `system` though, since Julia is better in it anyway.

**Comment by olivleno** [comment]
> Julia can call system commands directly, so why send it to omc in the first case?
> 

Good point.

**Comment by olivleno** [comment]
After:
```
result = simulate(omc,model_name;
    outputFormat = "csv",
#    simflags = "-r ref.csv"
    )
```
I wanted to call
`cp(result["resultFile"],res_file_path)`
but string resultFile is a posix string.
I wrote my own conversion function, but is there a built-in function for that? 
Or should simulate return a compliant string just like joinpath()?
