### ISSUE TITLE
Custom omc path on windows

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMJulia.jl#13]
I want to be able to use a specific omc executable in a `OMCSession` and to be able to use different executables at the same time.

I would like to do something like:
```julia
omc_1 = OMJulia.OMCSession()  # omc from OPENMODELICAHOME environment variable
omc_2 = OMJulia.OMCSession("D://workspace//OpenModelica//build//bin//omc.exe")  # omc specified with path to executable
```

**Comment by arun3688** [comment]
@AnHeuermann  The feature is added see https://github.com/OpenModelica/OMJulia.jl/commit/24844de4ecf5a1be84fd1047a2229deebc59a894

**Comment by AnHeuermann** [comment]
Is working with 73cf0834cbbad78a5b5fb1c23cb0ef2b6125158c
