### ISSUE TITLE
Register package at https://github.com/JuliaRegistries/Registrator.jl

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OMJulia.jl#18]
I am working on a package which is not fully documented yet and hosted at https://gitlab.com/christiankral/OMRemote.jl. My package depends on OMJulia.jl. When I try to refer to OMJulia.jl in my [Project.toml](https://gitlab.com/christiankral/OMRemote.jl/blob/master/Project.toml) the registrar at https://github.com/JuliaRegistries/Registrator.jl complains, that OMJulia.jl is not registered.

So is there a reason why the package is not registered at https://github.com/JuliaRegistries/Registrator.jl? This would definitely also simply also the installation of OMJulia as `Pkg.clone` does not have to be used.

**Comment by sjoelund** [comment]
We'll see how the PR goes. Don't know why Arun didn't register it before :) https://github.com/JuliaRegistries/General/pull/2654

**Comment by arun3688** [comment]
@sjoelund i did not know about this

**Comment by JKRT** [comment]
This was done in https://github.com/JuliaRegistries/General/pull/2654
