### ISSUE TITLE
omc stays running when julia is exited

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMJulia.jl#22]
Is there an option to close/shutdown an active `OMJulia.OMCSession()`?

When I run multiple OMCSessions and exit Julia afterwards there are still multiple processes `omc --interactive=zmq +z=julia.TrFYWsxcaT` running. The same happens if I kill an active OMCSession while omc is running some task (+ I get the same error as in ticket #12).
Those are preventing me from rebuilding `omc` and I have to search and kill them manually.

**Comment by sjoelund** [comment]
I guess sending the command quit() works... (OMPython has the same problem with no atexit hook closing the connection)

**Comment by arun3688** [comment]
@AnHeuermann  as martin said you can just use the command  obj.sendExpression("quit()") will close the session

**Comment by AnHeuermann** [comment]
Doing this results in
```julia
julia> omc=OMJulia.OMCSession();
julia> sendExpression(omc, "quit()")
ERROR: OMJulia.Parser.ParseError("Expected EOF, got output Any[Identifier(\"requested\"), Symbol(\",\"), Identifier(\"shutting\"), Identifier(\"server\"), Identifier(\"down\")]")
Stacktrace:
 [1] parseOM(::Array{Any,1}) at /home/aheuermann1/.julia/packages/OMJulia/ZLXEs/src/parser.jl:116
 [2] parseOM at /home/aheuermann1/.julia/packages/OMJulia/ZLXEs/src/parser.jl:122 [inlined]
 [3] sendExpression(::OMJulia.OMCSession, ::String) at /home/aheuermann1/.julia/packages/OMJulia/ZLXEs/src/OMJulia.jl:1015
 [4] top-level scope at none:0

```

**Comment by sjoelund** [comment]
Might need a try block for it. Or sending a command that is not parsed

**Comment by arun3688** [comment]
It is a parse error and you can see in the system process, that the omc process is killed

**Comment by arun3688** [comment]
@AnHeuermann , This is fixed with https://github.com/OpenModelica/OMJulia.jl/commit/ee363e4e561e3bbbd91c8ed6fe95d5d0b6300b15
you can use OMJulia.sendExpression(omc, "quit()",parsed=false)

**Comment by AnHeuermann** [comment]
It's still not working for me:
```Julia
julia> OMJulia.sendExpression(omc, "quit()",parsed=false)
ERROR: function sendExpression does not accept keyword arguments
Stacktrace:
 [1] kwfunc(::Any) at ./boot.jl:321
 [2] top-level scope at none:0
```

**Comment by AnHeuermann** [comment]
Oh.. you are right. But I only was able to get on the right version when using my local copy of the repository and activate that as package for development. But that's a different issue.
Thanks!
