### ISSUE TITLE
How to handle structural change of models

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OMJulia.jl#45]
### Modelica model

Consider the following [Modelica model](https://github.com/OpenModelica/OMJulia.jl/files/6843572/Test.mo.zip) which incorporates a structural change (number of states) depending on the integer variable `dyn`:

```modelica
model Test
  parameter Integer dyn = 1;
  parameter Real c = 1;
  Real x(start = c);
equation
  if dyn == 1 then
    der(x) = -c * x;
  else
    x = c;
  end if;
end Test;
```

### Case 1: Simulate model with `dyn = 1`

The default value is `dyn = 1`, so the parameter does not have to be changed for Case 1. I run the following code in Julia:

```julia
using OMJulia
mod = OMJulia.OMCSession()
ModelicaSystem(mod, "Test.mo", "Test")
simulate(mod)
dyn = getParameters(mod, "dyn")
x = getSolutions(mod, "x")[end][end]
println("dyn  = ", dyn, "\tx = ", x)
```

The result is `dyn  = 1	x = 0.3678794515339768` as expected.

### Case 2: Simulate model with `dyn = 0`

Now I want to change the structure of the model by setting `dyn = 0`. This implies that the number of states changes. 

Reading the documentation at https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/omjulia.html shows:

![image](https://user-images.githubusercontent.com/4184218/126217269-e6252771-3e43-41d9-9600-d8360cc44854.png)

but the following code does not:

```julia
setParameters(mod,"dyn=0")
OMJulia.buildModel(mod)
simulate(mod)
dyn = getParameters(mod, "dyn")
x = getSolutions(mod, "x")[end][end]
println("dyn  = ", dyn, "\tx = ", x)
```

Again the result `dyn  = 1	x = 0.3678794515339768` is the same as before. So obviously, the parameter `dyn` was **NOT** changed. Why?

Case 1 and Case 2 together are stored in file [Test.jl.zip](https://github.com/OpenModelica/OMJulia.jl/files/6843519/Test.jl.zip)

**Comment by christiankral** [comment]
Alternatively I tried to purely use the API applying `sendExpression(omc, ...)` as described in https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html. However, I could not find a way to change a parameter value before building and simulating a model, respectively. 

Is there an API call to change a parameter prior to building and simulating, respectively?

**Comment by christiankral** [comment]
Also note that `buildModel(mod)` does not work, but `OMJulia.buildModel(mod)` works.

**Comment by adrpo** [comment]
Use `setParameterValue(Test, dyn, 0)`.

**Comment by adrpo** [comment]
We should fix it so it tells you that the parameter you are trying to change is not modifiable without recompilation.

**Comment by adrpo** [comment]
If you need to set it deeper in a component, use setModifierValue.

**Comment by adrpo** [comment]
These will change the AST of the loaded program so you will need to recompile.

**Comment by arun3688** [comment]
@christiankral , Thanks for pointing out the issue, I tested myself it seems there is a bug when setting the `parameter values` of type `Integer`, You don't need to use the `buildModel()` to change the parameter values again. To check that I tried to change the Real parameter value `c` in the model 

```
julia> using OMJulia
julia> omc = OMJulia.OMCSession()
julia> ModelicaSystem(omc, "Test.mo", "Test")
julia> getParameters(omc, "c")
"1.0"
julia> setParameters(omc, "c=2.0")
"2.0"
julia> simulate(omc)
julia> x = getSolutions(omc, "c")[end][end]
2.0
julia> setParameters(omc, "c=4.0")
"4.0"
julia> simulate(omc)
julia> x = getSolutions(omc, "c")[end][end]
4.0
```
I will debug the problem and try to fix the problem with `ModelicaSystem` Constructor

**Comment by christiankral** [comment]
> Use `setParameterValue(Test, dyn, 0)`.

Thanks for this comment. Using `sendExpression(omc, "setParameterValue(Test, dyn, 0)")` in OMJulia does change the parameter. Unfortunately, `setParameterValue` is not yet documented on https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/search.html?q=setParameterValue

**Comment by adrpo** [comment]
Yes, some of the API is not documented as we dont want to encourage its use because it changes quite often.

**Comment by arun3688** [comment]
@christiankral , yes that is true, it is undocumented,  and also i misunderstood your question, and I was wrong with my comments earlier that setParameters() does not work with parameter of type `Integer` , The `setParameters() ` API works, but the `API just overrides the parameter values at run time using the `-override` Flag, but it does not gives warning something like below

```
# ./Test.exe -override="dyn=2"
stdout            | warning | It is not possible to override the following quantity: dyn
|                 | |       | It seems to be structural, final, protected or evaluated or has a non-constant binding.
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
```

I will do some changes to the API to give better warning and also as you pointed out `buildModel()` API is not exported and hence you could not use

**Comment by christiankral** [comment]
@arun3688 A workaround for integers not yet working is to simply change `dyn` from `Integer` to `Real`:

```modelica
model Test
  parameter Real dyn = 1;
  parameter Real c = 1;
  Real x(start = c);
equation
  if dyn == 1 then
    der(x) = -c * x;
  else
    x = c;
  end if;
end Test;
```

Again, the change of parameter `dyn` causes a structural change of the model and requires re-building the code.

Applying the following Julia code 

```julia
using OMJulia
mod = OMJulia.OMCSession()
ModelicaSystem(mod, "Test.mo", "Test")
setParameters(mod,"dyn=0")
OMJulia.buildModel(mod)
simulate(mod)
dyn = getParameters(mod, "dyn")
x = getSolutions(mod, "x")[end][end]
println("dyn  = ", dyn, "\tx = ", x)
```

does still not lead to the expexted result. The output of this Julia script is: `dyn  = 1.0 x = 0.3678794515339768`


So apparently `setParameters(mod,"dyn=0")` is not applied correctly even in case 
of `dyn` being a parameter of type `Real`. When 

- replacing `setParameters(mod,"dyn=0")`
- by `sendExpression(mod, "setParameterValue(Test, dyn, 0)")`

the output of the Julia script is OK: `dyn  = 1.0	x = 0.3678794515339768`

**Comment by christiankral** [comment]
This, however, also works for `dyn` being of type `Integer`.

**Comment by arun3688** [comment]
> This, however, also works for `dyn` being of type `Integer`.

Yes it works, but you cannot override the parameter value from `dyn=1` to `dyn=0 ` using the `setParameters()` API because it uses a different approach to apply the new values to the parameters and it is done during run-time using the `-override` flag since `dyn` is a structural parameter, it is not possible to change the value and you do not get proper warning message

**Comment by arun3688** [comment]
@christiankral , I have now exported `buildModel()` API, and also improved the error reporting, Now you can use the `ModelicaSystem() and sendExpression() `in combination and rebuild the model using `buildModel()`, An example of such combination is given below

```
julia> using OMJulia                                                                                                                                                                                                                                                                                                                                                                    
julia> omc = OMJulia.OMCSession()                                                                                                                                                                                                                                                                                                                                                       
julia> ModelicaSystem(omc, "Test.mo", "Test")                                                                                                                                                                                                                                                                                                                                           
julia> setParameters(omc, "dyn=0")                                                                                                                                                          
"0"                                                                                                                                                                                                                                                                                                                                                                                     
julia> simulate(omc)                                                                                                                                                                        
stdout            | warning | It is not possible to override the following quantity: dyn                                                                                                    
|                 | |       | It seems to be structural, final, protected or evaluated or has a non-constant binding.                                                                       
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.                                                                                             
LOG_SUCCESS       | info    | The simulation finished successfully.                                                                                                                         
 
## use sendExpression() to do some changes                                                                                                                                                                                                                                                                                                                                                                                      
julia> sendExpression(omc, "setParameterValue(Test,dyn,0)")                                                                                                                                 
:Ok 
## rebuild the model again                                                                                                                                                                                                                                                                                                                                                                                     
julia> buildModel(omc)                                                                                                                                                                                                                                                                                                                                                                  
julia> simulate(omc)                                                                                                                                                                        
stdout            | warning | It is not possible to override the following quantity: dyn                                                                                                    
|                 | |       | It seems to be structural, final, protected or evaluated or has a non-constant binding.                                                                       
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.                                                                                             
LOG_SUCCESS       | info    | The simulation finished successfully.                                                                                                                         
                                                                                                                                                                                            
julia> x = getSolutions(omc, "dyn")[end][end]                                                                                                                                               
0.0                                                                                                                                                                                                                                                                                                                                                                                     
julia> x = getSolutions(omc, "x")[end][end]                                                                                                                                                 
1.0  
```

**Comment by christiankral** [comment]
Very good. Thanks a lot.

From my point of view we can close this ticket.

**Comment by christiankral** [comment]
> We should fix it so it tells you that the parameter you are trying to change is not modifiable without recompilation.

@arun3688 @adrpo Is this still going to be done? This would possibly support a more structured solution of #47 for my purpose.

**Comment by arun3688** [comment]
@christiankral  I guess this commit https://github.com/OpenModelica/OMJulia.jl/commit/83e39739c1f6549642f4ee64600a44be9e22409a is telling you the message you want , that it is not possible to override dyn due to `structural` 

julia> simulate(omc)                                                                                                                                                                        
stdout            | warning | It is not possible to override the following quantity: dyn                                                                                                    
|                 | |       | It seems to be structural, final, protected or evaluated or has a non-constant binding.                                                                       
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.                                                                                             
LOG_SUCCESS       | info    | The simulation finished successfully.

**Comment by arun3688** [comment]
@christiankral I found a more better way to report about `structural parameter` and report the error message directly when using the `setParameters()` API, So that users are aware that these parameters are not modifiable. I will implement it tomorrow

**Comment by christiankral** [comment]
Thanks @arun3688
