### ISSUE TITLE
buildModel() is not working

### ISSUE THREAD

**Issue by Amuri44** [OpenModelica/OMJulia.jl#58]
I am trying to implement the code in julia:
https://openmodelica.org/doc/OpenModelicaUsersGuide/1.18/scripting_api.html#simulation-parameter-sweep
the loadFile is working but the buildModel (i.e., sendExpression(omc,"buildModel(BouncingBall)");) is not (although it works in omshell). Any idea or reason for that?

**Comment by arun3688** [comment]
@Amuri44 , there is an extra `parenthesis `and `semicolon`, It should be `sendExpression(omc, "buildModel(BouncingBall)")` also please note that if there are some problems you should always use `getErrorString()`  to see the error message `sendExpression(omc, "getErrorString()")`, So your code should be like this 

```
sendExpression(omc, "buildModel(BouncingBall)")
sendExpression(omc, "getErrorString()")
```

**Comment by Amuri44** [comment]
@arun3688  Thanks for your reply!
I copy also your code and it did not give any results in julia (it gave as below)

[ Info: Path to zmq file="C:\Users\amroa\AppData\Local\Temp\openmodelica.port.julia.zRhLDU5UE7"
""
julia>

**Comment by arun3688** [comment]
> sendExpression(omc,"buildModel("C:/Users/amroa/AppData/Local/Temp/OpenModelica/BouncingBall")")
> sendExpression(omc,"getErrorString()")

This is wrong, you cannot use `buildModel`  like that, can you paste your full code

**Comment by Amuri44** [comment]
> Thanks for your reply! I have the below issues: 1- I found that the results are in a different folder. For this issue, how to set an arbitrary path for the resulting files in julia?
> 
> 2- After I continue in the code, the below part is not creating the three results files (i.e. "_res.mat" ). Could you please help to check it?
> 
> for i in 1:3 value = 0.7 + i; sendExpression(omc,"system(\"C:/Users/amroa/OneDrive - polymtl.ca/AmroAlsabbagh/Code/Julia/BouncingBall -override=e=\"+String(value)+\" -r=BouncingBall\" + String(i) + \"_res.mat\")"); sendExpression(omc,"getErrorString()"); end
