### ISSUE TITLE
Add OSI-approved license to OMJulia top level folder

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMJulia.jl#61]
Currently https://github.com/JuliaRegistries/General/pull/58444 fails, because of the missing license file, so we can't update our OMJulia version in the Julia general regestry.

OMJulia source files are using the [OSMC-PL](https://www.openmodelica.org/developersresources/contributor-license-agreement?id=56:full-license) license, see e.g. https://github.com/OpenModelica/OMJulia.jl/blob/master/src/OMJulia.jl#L1-L27.

Our OSMC-PL license is problematic for adding OMJulia to the general registry since it is not part of the [OSI-approved license](https://opensource.org/licenses/alphabetical).

Is there any reason to not just use a license that is OSI-aproved and allowes other to change OMJulia.jl? E.g. MIT license.
This package is only a API for OpenModelica and OpenModelica is not shipped with it.
So all generated code by omc is still under OSMC-PL license.

Or we use GPL-3.0, but then nobody is allowed to change OMJulia.

**Comment by AnHeuermann** [comment]
@casella Maybe we should discuss this is the next developer meeting, or does the OSMC board need to decide this?

**Comment by casella** [comment]
> Or we use GPL-3.0, but then nobody is allowed to change OMJulia.

To the contrary, anybody can do that, _provided they make the changed code publicly available if they release it_. I don't see any problem with that. @AnHeuermann please remind me this issue during the next webmeeting.

**Comment by bilderbuchi** [comment]
> So all generated code by omc is still under OSMC-PL license.

Isn't code _generated_ by omc under the [runtime license](https://openmodelica.org/osmc-pl/osmc-pl-1.2-runtime.txt), isn't that what that license is for? 

> We should use the same license here as for the other OpenModelica Julia packages.

(At least MetaModelica.jl seems [to use an old version of the RT license](https://github.com/OpenModelica/MetaModelica.jl/blob/master/LICENSE.md), with a missing mention of BSD-3)
BSD New/BSD-3 might be a more natural OSI-compatible fit than MIT (as this is also an option in the RT license)?

**Comment by casella** [comment]
The OSMC-PL license is meant for the source code of _the tool_, not for the generated source code of _user's models_.  That is to prevent non OSMC-members to change the code of OpenModelica for their purposes, make it closed-source and sell without any benefit for the OSMC.

There is no reason to use the OSMC-PL license for the _generated code_ of user's models. User's models are the property of the user and we should have no business with that, no string attached. Commercial tools do it, forcing third parties that want to run your compiled model to also have a license. That has never been our intention. So, we use the **OSMC-PL runtime** license, that also includes BSD-3, which basically allows you do do anything you want with the code, except claiming you wrote it.

**Comment by bilderbuchi** [comment]
> That is to prevent non OSMC-members to **change** the code of OpenModelica for their purposes, make it closed-source and sell without any benefit for the OSMC.

The case of _changing_ OM code is very clear, but what about **using OM unchanged**? Possibly that is what is surfaced in discussions in components wrapping/driving OM, like here or in https://github.com/OpenModelica/OMPython/issues/153.



For example, let us consider that OMJulia or OMPython (or other ancillary/driver packages) are used unchanged/imported by some entity in some software S that e.g. automates model execution/runs tests/does machine learning on models/whatever currently hip topic.
The end user would install OM separately (under OSMC-PL | GPL3) to obtain `omc` and run it.

The first question to resolve is if the use of `omc` via sockets/pipes (like OMJulia/OMPython do) consists of [aggregation](https://www.gnu.org/licenses/gpl-faq#MereAggregation). It seems to me (**IANAL**) this should be an aggregate, and as such the whole is not a "combined program", and as such **`omc`'s** GPL option would not apply to the software S.

Assuming that is correct, then the license of OMJulia or OMPython itself becomes relevant.
As one typically uses/`import`s those in whatever other software S, I think it's a given that S will form a combined work with the wrapper package.

**Option A)** If OMJulia/OMPython are licensed under OSMC-PL/GPL-3, this means software S will also need to be under OSMC-PL/GPL-3. 
Non-OSMC members (e.g. random folks from the Julia community) will have to license their package using it under GPL-3.

**Option B)** If OMJulia/OMPython are licensed under OSMC-PL-RT/GPL-3/BSD-3, this is more permissive and would allow licensing S under OSMC-PL/GPL-3/BSD-3. 
Then, non-OSMC members would be allowed to create a _BSD-licensed or proprietary_ software S that _uses_ OM/omc unmodified (if the end user installs it separately).

The question is if the OSMC intends to enable use according to option A) or option B).
I think the answer then decides if the license for wrapper/driver/ancillary/aggregated software in the OM ecosystem shall be OSMC-PL or OSMC-PL-RT, and those can be harmonised/updated accordingly.

**Comment by casella** [comment]
> The first question to resolve is if the use of `omc` when communicating via sockets/pipes (like OMJulia/OMPython do) consists of [aggregation](https://www.gnu.org/licenses/gpl-faq#MereAggregation). It seems to me (**IANAL**) this should be an aggregate, and as such the whole is not a "combined program", and as such **`omc`'s** GPL option should not apply to the software S.

IANAL either, but the text of GPL v3 seems very clear to me
> This License explicitly affirms your **unlimited** permission to run the **unmodified** Program.

Whether the input to the program comes from a file, or a socket, or a floo network port, should be irrelevant. For example, GNU is released under GPL.  If you run `grep "somestring" input.txt | myprogram` that doesn't require you to release myprogram as GPL if you want to convey it to others.

> Assuming that is correct, then the license of OMJulia or OMPython itself becomes relevant. As one typically uses/`import`s those in whatever other software S, I think it's a given that S will form a combined work with the wrapper package.

Makes sens.
 
> **Option A)** If OMJulia/OMPython are licensed under OSMC-PL/GPL-3, this means software S will also need to be under OSMC-PL/GPL-3. Non-OSMC members (e.g. random folks from the Julia community) will have to distribute their package using OMJulia under GPL-3.
> 
> **Option B)** If OMJulia/OMPython are licensed under OSMC-PL-RT/GPL-3/BSD-3, this is more permissive and would allow licensing S under OSMC-PL/GPL-3/BSD-3. Then, non-OSMC members would be allowed to distribute a _BSD-licensed or proprietary_ software S that _uses_ OM/omc unmodified (if the end user installs it separately).

That's clear.

> The question is if the OSMC intends to enable use according to option A) or option B). I think the answer then decides if the license for wrapper/driver/ancillary/aggregated software in the OM ecosystem shall be OSMC-PL or OSMC-PL-RT, and those can be harmonised/updated accordingly.

I think we should discuss this with the Board. As far as I am concerned, OMJulia and OMPython are just thin wrappers around omc, to ease the communication with it, so I would use the **OSMC-PL runtime** license for them. Unless we consider using OMJulia and OMPython as a "premium option" that requires OSMC membership to use them with non-GPL v3 software. That doesn't make much sense to me, personally, but it's not up to me to decide.

**Comment by bilderbuchi** [comment]
> > The first question to resolve is if the use of `omc` when communicating via sockets/pipes (like OMJulia/OMPython do) consists of [aggregation](https://www.gnu.org/licenses/gpl-faq#MereAggregation). It seems to me (**IANAL**) this should be an aggregate, and as such the whole is not a "combined program", and as such **`omc`'s** GPL option should not apply to the software S.
> 
> IANAL either, but the text of GPL v3 seems very clear to me
> 
> > This License explicitly affirms your **unlimited** permission to run the **unmodified** Program.
> 

You are lucky, then. :-) 
It's not without reason that in the FAQs for the GPL, there are [several ](https://www.gnu.org/licenses/gpl-faq#MereAggregation) [items ](https://www.gnu.org/licenses/gpl-faq#LinkingWithGPL) [concerning ](https://www.gnu.org/licenses/gpl-faq#GPLPlugins) [the ](https://www.gnu.org/licenses/gpl-faq#GPLAndPlugins) [question ](https://www.gnu.org/licenses/gpl-faq#GPLAndPlugins) [if ](https://www.gnu.org/licenses/gpl-faq#AggregateContainers) a dependency's GPL applies to the main work. 

IIUC, the question of aggregation-or-not is primarily relevant for terms of *distribution* , not *use*/*running the program*. 

> > The question is if the OSMC intends to enable use according to option A) or option B). I think the answer then decides if the license for wrapper/driver/ancillary/aggregated software in the OM ecosystem shall be OSMC-PL or OSMC-PL-RT, and those can be harmonised/updated accordingly.
> 
> I think we should discuss this with the Board. As far as I am concerned, OMJulia and OMPython are just thin wrappers around omc, to ease the communication with it, so I would use the **OSMC-PL runtime** license for them. Unless we consider using OMJulia and OMPython as a "premium option" that requires OSMC membership to use them with non-GPL v3 software. That doesn't make much sense to me, personally, but it's not up to me to decide.

Sounds reasonable!

**Comment by bilderbuchi** [comment]
On the topic of registering the package, it [seems](https://github.com/JuliaRegistries/General/issues/48137#issuecomment-960864015) that dual-licensing packages is not a problem. 
As the OSMC license (RT or not) is effectively a dual license, it seems to me that it can be clarified in the PR that an OSI-approved license (GPL-3 or GPL-3/BSD-3) is available to users who need that?

An issue might be that [they seem to expect](https://github.com/JuliaRegistries/General/issues/48137#issuecomment-960864015) that you change the LICENSE file to the OSI-approved license and include a note concerning the dual licensing, but that can maybe be clarified in a discussion with humans (not the automated machinery).

**Comment by bilderbuchi** [comment]
> I think we should discuss this with the Board. As far as I am concerned, OMJulia and OMPython are just thin wrappers around omc, to ease the communication with it, so I would use the **OSMC-PL runtime** license for them. Unless we consider using OMJulia and OMPython as a "premium option" that requires OSMC membership to use them with non-GPL v3 software. That doesn't make much sense to me, personally, but it's not up to me to decide.

@casella, as you have closed this, can you report on the outcome of this discussion with the board (if you had it)? 
In this issue, you said that you would use the **OSMC-PL runtime** license. 

In #70, you merged a license file that states in the first line that it uses the OSMC-PL version 1.2, immediately followed by something that looks like the OSMC-PL-**RT** header (notice the presence of the BSD license), not quite identical to either https://openmodelica.org/osmc-pl/osmc-pl-1.2-runtime.txt or https://openmodelica.org/osmc-pl/osmc-pl-1.2-header.txt. This is then followed by what I presume is the rest of the OSMC-PL.

Well, I'm confused -- has your intent changed to license this under OSMC-PL instead of OSMC-PL-RT? If so, can you say what caused the change of mind from your previous assessment (quoted above), and why is the BSD mentioned in the license file from https://github.com/OpenModelica/OMJulia.jl/pull/70/files?

**Comment by casella** [comment]
Gosh, I wish somebody else could take care of these issues 😅

**Comment by casella** [comment]
In fact, OMJulia.jl already includes that information. I'll just report it to the LICENSE.md file

**Comment by casella** [comment]
OK, this was in fact easier than I thought.
- The source code files already have the correct runtime license info (i.e. one can pick between BSD 3-clause, GPL v3, and OSMC-PL)
- I reported this information in the README.md file
- I also added a LICENSE.md file, reporting the most permissive of the three licenses (i.e. BSD 3-clause) so it is automatically recognized by license-aware bots.

@DilumAluthge, I hope this is fine for you.

**Comment by casella** [comment]
And, thanks to @bilderbuchi for watching over my shoulders 😅

**Comment by bilderbuchi** [comment]
Sure, no problem!

> Gosh, I wish somebody else could take care of these issues 😅

I seem to be attracting the attention of license-related issues (https://github.com/OpenModelica/OpenModelica/issues/7612) 😅 

If you want, I can try to collect information on the license status (at least the license files, checking all sources will be quite the effort) for the most relevant/active repos in the OM org in one place, e.g. an issue in the OM tracker. 
I'd need clear guidance (or at least subsequent feedback) on what the respective licenses _should_ be. 😀 For example, I think I can take away from this discussion that "scripting"/wrapper packages should generally be under OSMC-PL-RT, all others under OSMC-PL.

**Comment by casella** [comment]
> If you want, I can try to collect information on the license status (at least the readme/license files, checking all sources will be quite the effort) for the most relevant/active repos in the OM org in one place, e.g. an issue in the OM tracker.

That would be very useful indeed.

> I'd need clear guidance (or at least subsequent feedback) on what the respective licenses _should_ be. 

Sure. This also requires some time and effort, but it's much less once the relevant information has been properly processed.

> 😀 For example, I think I can take away from this discussion that "scripting"/wrapper packages should generally be under OSMC-PL-RT 1.2, all others under OSMC-PL 1.2.

Absolutely. BTW, I guess we haven't formally defined "OSMC-PL_RT", which basically means OSMC-PL _or_ BSD 3-clause _or_ GPL v3.

BTW, we are now changing GPL v3 to GPL Affero (to cover software-as-a-service usage of OMC), so I guess that will need a further round of license info harmonization.

**Comment by bilderbuchi** [comment]
> Absolutely. BTW, I guess we haven't formally defined "OSMC-PL_RT", which basically means OSMC-PL _or_ BSD 3-clause _or_ GPL v3. Or is this stated in some official online document?

I agree. It might be good to introduce this at some point, including versioning (in lockstep with OSMC-PL versions, probably). In the style of [SPDX identifiers](https://spdx.org/licenses/), I'd avoid the underscore and use `OSMC-PL-RT`, though. 
Possibly include the version in the identifier, so `OSMC-PL-1.2` and `OSMC-PL-RT-1.2`.

**Comment by bilderbuchi** [comment]
Also, you might have a case to get the OSMC-PL added to the SPDX license list, which would enable using `OSMC-PL-1.2` in project metadata, get picked up by Github license display (and other package managers like probably Julia's), etc. 
There's a [list of criteria](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md), and based on the source-available nature, the GPL option/mode, and already established use it seems it could go in.

**Comment by bilderbuchi** [comment]
> BTW, we are now changing GPL v3 to GPL Affero (to cover software-as-a-service usage of OMC), so I guess that will need a further round of license info harmonization.

Ah, interesting. You probably realize that that will make adoption (in companies) more difficult? For example, in [this](https://blueoakcouncil.org/company-policy) template company policy for OSS use, OM would drop from the "Caution (internal use ok without legal approval)" category to the "Stop (legal approval needed for any use)" category. Is that intentional?
Did you already have problems with companies selling OM through a web interface?
