### ISSUE TITLE
Closing of OMCSession

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OMJulia.jl#62]
When I run perform batch processes based on OMJulia, several hundret calls of `OMCSession` are performed. 

![image](https://user-images.githubusercontent.com/4184218/172993312-6d8baddd-fc16-4d32-b00d-8ef5de0c09a7.png)

After that I have many abandonded processes which push the RAM consumption of my (Linux) computer to its limits.

I could neither find in the documentation nor in the examples, how I can free the memory resources by closing the used `OMCSession`. My question thus refers to an equivalence of `close`, used after openening and writing a file. Is such closing alread implemented? If not, it possibly should be implemented.

**Comment by arun3688** [comment]
@christiankral to delete a session you have to use `quit()`  like `sendExpression(omc, "quit()")`

**Comment by christiankral** [comment]
I tried the following:

```
using OMJulia
mod = OMJulia.OMCSession()
sendExpression(mod, "quit()")
```

The third line causes an error message:

```
ERROR: OMJulia.Parser.ParseError("Expected EOF, got output Any[OMJulia.Parser.Identifier(\"requested\"), Symbol(\",\"), OMJulia.Parser.Identifier(\"shutting\"), OMJulia.Parser.Identifier(\"server\"), OMJulia.Parser.Identifier(\"down\")]")
Stacktrace:
 [1] parseOM(tokens::Vector{Any})
   @ OMJulia.Parser ~/.julia/packages/OMJulia/GiA9Y/src/parser.jl:121
 [2] parseOM
   @ ~/.julia/packages/OMJulia/GiA9Y/src/parser.jl:127 [inlined]
 [3] sendExpression(omc::OMJulia.OMCSession, expr::String; parsed::Bool)
   @ OMJulia ~/.julia/packages/OMJulia/GiA9Y/src/OMJulia.jl:184
 [4] sendExpression(omc::OMJulia.OMCSession, expr::String)
   @ OMJulia ~/.julia/packages/OMJulia/GiA9Y/src/OMJulia.jl:180
 [5] top-level scope
   @ REPL[3]:1
```

**Comment by arun3688** [comment]
@christiankral , It seems there is a problem with Julia parser when parsing the results from omc, please disable the parser like below

```
julia> omc = OMJulia.OMCSession()
julia> sendExpression(omc, "getVersion()")
"OpenModelica v1.20.0-dev-101-g55feca18f5 (64-bit)"
julia> sendExpression(omc, "quit()", parsed=false)
"quit requested, shutting server down\n"
```

**Comment by christiankral** [comment]
OK. the option `parsed=false` seems to work:

```
sendExpression(omc, "getVersion()")
"OpenModelica 1.20.0~dev-121-gfa321a0"
sendExpression(omc, "quit()", parsed=false)
"quit requested, shutting server down\n"
```

**Comment by christiankral** [comment]
@arun3688 Is the option `parsed=false` already the full solution to my request or is it a parsing issue that needs to be solved?

**Comment by arun3688** [comment]
@christiankral Well the immediate solution is to use `parsed = false`, but offcourse we need to fix the parser

**Comment by Wardi0** [comment]
@arun3688 Apologies that this is an old thread but I am also encountering issues closing OMCSessions. Using `sendExpression(omc, "quit()")` produces `ERROR: OMJulia.Parser.ParseError` as @christiankral posted above. However, when I try `sendExpression(omc, "quit()", parsed=false)`,  I get a method error:

```
ERROR: MethodError: no method matching sendExpression(::OMJulia.OMCSession, ::String; parsed=false)
Closest candidates are:
  sendExpression(::Any, ::Any) at ~/.julia/packages/OMJulia/ZLXEs/src/OMJulia.jl:1012 got unsupported keyword argument "parsed"                                                            
Stacktrace:
 [1] test()
   @ Main.OMJ_V2 ./REPL[53]:15
 [2] top-level scope
   @ REPL[54]:1```

**Comment by arun3688** [comment]
Hi OliWard,

From the error message i can see that you are using old version of OMJulia,
please update your OMJulia package with the latest master and perform the
test.



regards
arun
