### ISSUE TITLE
OMJulia not working inside Docker container

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMJulia.jl#67]
## Description

I have a Julia package that is building the documentation inside a Docker container using Documenter.jl.

My CI fails to build the documentation, because OMJulia doesn't work inside a docker container, because the ZMQ server port file can't be created.

```julia
julia> using OMJulia
julia> omc=OMJulia.OMCSession()
[ Info: Path to zmq file="/tmp/openmodelica..port.julia.s7DsM0rBD2"
Execution failed!
ERROR: Timeout: ZMQ server port file "/tmp/openmodelica..port.julia.s7DsM0rBD2" not created yet.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] OMJulia.OMCSession(omc::Nothing)
   @ OMJulia ~/.julia/packages/OMJulia/EXbLd/src/OMJulia.jl:170
 [3] OMJulia.OMCSession()
   @ OMJulia ~/.julia/packages/OMJulia/EXbLd/src/OMJulia.jl:88
 [4] top-level scope
   @ REPL[13]:1
```

## How to reproducer

Create a `dockerfile` with:

```dockerfile
FROM julia

# Get OpenModelica repo and key
RUN apt-get update && \
    apt-get install -qy \
      ca-certificates \
      curl \
      gnupg \
      lsb-release && \
    curl -fsSL http://build.openmodelica.org/apt/openmodelica.asc | gpg --dearmor -o /usr/share/keyrings/openmodelica-keyring.gpg && \
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/openmodelica-keyring.gpg] https://build.openmodelica.org/apt \
      $(lsb_release -cs) nightly" | tee /etc/apt/sources.list.d/openmodelica.list > /dev/null

# Install OpenModelica nightly
RUN apt update && \
    apt install -qy openmodelica

# Set USER
ENV USER=${USER_NAME}
```

Build the container
```bash
$ docker build --build-arg USER_NAME=$(whoami) -t julia-with-omc .
```

Start the container and execute Julia commands
```bash
$ docker run --rm -it julia-with-omc julia
(@v1.8) pkg> add https://github.com/OpenModelica/OMJulia.jl#master
julia> using OMJulia
julia> omc=OMJulia.OMCSession()
```

**Comment by AnHeuermann** [comment]
With some debugging I could locate the issue:

```bash
root@e3c6ff0eebc7:/dir omc --interactive=zmq +z=julia.50a4pzOkyM
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!
```

This is a reasonable restriction, but OMJulia should return the full error message. I'll try to redirect `stdout` and `stderr` into a buffer and print, if the process fails.

**Comment by casella** [comment]
Wow, let's try to avoid people using omc as a Trojan horse 😅

**Comment by arun3688** [comment]
@AnHeuermann  Inside a docker container omc cannot be run as a root users,  we should always run as a non root user, see an example https://github.com/OpenModelica/jupyter-openmodelica/blob/master/Dockerfile

**Comment by AnHeuermann** [comment]
The point is, that the error message was not displayed by OMJulia.

I'm fine with the restriction in itself. Actually I'm running the docker daemon as a non-root user, so for me the user is called root, but mapped to my host user.
