### ISSUE TITLE
OMJulia scripting api docu: link to OMJulia functions

### ISSUE THREAD

**Issue by olivleno** [OpenModelica/OMJulia.jl#87]
The scripting api gives not indication whether the function has to be called as string argument or if there is a convenience function available.

It would be great if the api functions were providing links the julia functions, if they exist.

Also it would be helpful if there were references from the [OMJulia Sensitivity Analysis](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omjulia.html) paragraph, which is just explaining the syntax, to the [parameter sensitivity](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/parametersensitivity.html) section, which explains the mathematical background.

**Comment by AnHeuermann** [comment]
We updated the OMJulia.jl documentation. Can you find the information you are looking for in https://openmodelica.github.io/OMJulia.jl/dev/?
