### ISSUE TITLE
Kill dangling omc process

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMJulia.jl#96]
When a OMCSession isn't quit the omc process stays running forever.

Maybe [`finalizer`](https://docs.julialang.org/en/v1.9/base/base/#Base.finalizer) is an option to kill the omc process when the memory for `OMCSession` is no longer accessible.

**Comment by AnHeuermann** [comment]
We can also try something similar as in OMPython: https://github.com/OpenModelica/OMPython/blob/master/OMPython/__init__.py#L167-L193

I think we shouldn't wait for `quit()` in OMJulia.sendExpression. Adding a timeout or a special quit function that has some timeout and would be a good idea.

**Comment by AnHeuermann** [comment]
Related to https://github.com/OpenModelica/OMJulia.jl/issues/32

**Comment by arun3688** [comment]
@AnHeuermann I guess `kill(omc.omcprocess)` is the better than `quit` as you said sometime omc process are alive even after using `quit`

**Comment by AnHeuermann** [comment]
I'm working on a timeout function that first tries `quit()` and then checks if the process is still running and kills.
